version = 1

exclude_patterns = [
  "bin/**",
  "**/node_modules/",
  "js/**/*.min.js"
]

test_patterns = [
  "src/test/**/*.*",
  "src/accessibilityTest/**/*.*"
]

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "17"
  language_version = "1.9"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "browser",
    "nodejs"
  ]

[[analyzers]]
name = "test-coverage"
enabled = true
