version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/idanelh/ktlint
  ktlint: idanelh/ktlint@1.0.1

jobs:
  ktlint:
    docker:
      - image: cimg/openjdk:21.0.2-browsers
    steps:
      - checkout
      - ktlint/install:
          version: 1.1.1
      - ktlint/lint:
          working-directory: ~/project

  detekt:
    docker:
      - image: cimg/openjdk:21.0-browsers
    environment:
      DETEKT_VERSION: "1.23.3"
    steps:
      - checkout
      - run:
          name: Install Detekt
          # language="shell script"
          command: |
            curl -sSLO "https://github.com/detekt/detekt/releases/download/v$DETEKT_VERSION/detekt-cli-$DETEKT_VERSION.zip"
            unzip "detekt-cli-$DETEKT_VERSION.zip"
            chmod +x "./detekt-cli-$DETEKT_VERSION/bin/detekt-cli"
            ./detekt-cli-$DETEKT_VERSION/bin/detekt-cli --report md:detekt.md
      - store_artifacts:
          path: detekt.md
          destination: detekt.md

  compile:
    docker:
      - image: cimg/openjdk:21.0.2-browsers
    steps:
      - checkout

      - restore_cache:
          name: Restore npm Cache
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-eps-

      - run:
          name: Generate Gradle Cache Key
          command: md5sum **/*.kts gradle.properties gradle/wrapper/gradle-wrapper.properties > /tmp/deps-gradle-cache-key
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "/tmp/deps-gradle-cache-key" }}
            - v1-gradle-deps-

      - run:
          name: Compile App & Tests
          command: ./gradlew testClasses --build-cache

      - save_cache:
          name: Save npm Cache
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
              - node_modules

      - save_cache:
          key: v1-gradle-deps-{{ checksum "/tmp/deps-gradle-cache-key" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

  test:
    docker:
      - image: cimg/openjdk:21.0.2-browsers
    steps:
      - checkout

      - restore_cache:
          name: Restore npm Cache
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-eps-

      - run:
          name: Generate Gradle Cache Key
          command: md5sum **/*.kts gradle.properties gradle/wrapper/gradle-wrapper.properties > /tmp/deps-gradle-cache-key
      - restore_cache:
          name: Restore Gradle Cache
          keys:
            - v1-gradle-deps-{{ checksum "/tmp/deps-gradle-cache-key" }}
            - v1-gradle-deps-

      - run:
          name: Run Tests & Checks
          command: ./gradlew check --build-cache

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp -v {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - save_cache:
          name: Save npm Cache
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - save_cache:
          key: v1-gradle-deps-{{ checksum "/tmp/deps-gradle-cache-key" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

workflows:
  build_and_test:
    jobs:
      - ktlint
      - detekt
      - compile:
          requires:
            - ktlint
            - detekt
      - test:
          requires:
            - compile