version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/idanelh/ktlint
  ktlint: idanelh/ktlint@1.0.1

jobs:
  ktlint:
    docker:
      - image: cimg/openjdk:21.0.2-browsers
    steps:
      - checkout
      - ktlint/install:
          version: 1.1.1
      - ktlint/lint:
          working-directory: ~/project

  compile:
    docker:
      - image: cimg/openjdk:21.0.2-browsers
    steps:
      - checkout

      - run:
          name: Generate Gradle Cache Key
          command: md5sum **/*.kts gradle.properties gradle/wrapper/gradle-wrapper.properties package-lock.json > /tmp/deps-cache-key

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "/tmp/deps-cache-key" }}
            - v1-deps-

      - run:
          name: Compile App & Tests
          command: ./gradlew testClasses

      - save_cache:
          key: v1-deps-{{ checksum "/tmp/deps-cache-key" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - node_modules

  test:
    docker:
      - image: cimg/openjdk:21.0.2-browsers
    steps:
      - checkout
      - run: ./gradlew check

workflows:
  build_and_test:
    jobs:
      - ktlint
      - compile:
          requires:
            - ktlint
      - test:
          requires:
            - compile