version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/idanelh/ktlint
  ktlint: idanelh/ktlint@1.0.1
  node: circleci/node@5.2.0

executors:
  gradle-executor:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:21.0.2-browsers

commands:
  # https://circleci.com/docs/reusing-config/#authoring-reusable-commands
  restore_gradle_cache:
    description: "Restore Gradle wrapper and dependencies caches"
    steps:
      - restore_cache:
          name: Restore gradle-wrapper cache
          keys:
            - v3-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v3-gradle-wrapper-
      - run:
          name: Generate gradle cache key
          command: md5sum **/*.kts gradle.properties > /tmp/deps-gradle-cache-key
      - restore_cache:
          name: Restore Gradle cache
          keys:
            - v3-gradle-deps-{{ checksum "/tmp/deps-gradle-cache-key" }}
            - v3-gradle-deps-

  restore_npm_cache:
    description: "Restore npm cache"
    steps:
      - restore_cache:
          name: Restore npm cache
          keys:
            - v3-npm-deps-{{ checksum "package-lock.json" }}
            - v3-npm-deps-

  save_gradle_cache:
    description: "Save Gradle wrapper and dependencies cache"
    steps:
      - save_cache:
          name: Save Gradle wrapper cache
          paths:
            - ~/.gradle/wrapper
          key: v3-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Generate gradle cache key
          command: md5sum **/*.kts gradle.properties > /tmp/deps-gradle-cache-key
      - save_cache:
          name: Save Gradle cache
          key: v3-gradle-deps-{{ checksum "/tmp/deps-gradle-cache-key" }}
          paths:
            - ~/.gradle/caches

  save_npm_cache:
    description: "Save npm cache"
    steps:
      - save_cache:
          name: Save npm cache
          key: v3-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  store_test_results_artifacts:
    description: "Store test results"
    steps:
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always

jobs:
  ktlint:
    docker:
      - image: cimg/openjdk:21.0.2-browsers
    steps:
      - checkout
      - ktlint/install:
          version: 1.1.1
      - ktlint/lint:
          working-directory: ~/project

  detekt:
    docker:
      - image: cimg/openjdk:21.0-browsers
    environment:
      DETEKT_VERSION: "1.23.3"
    steps:
      - checkout
      - run:
          name: Install Detekt
          # language="shell script"
          command: |
            curl -sSLO "https://github.com/detekt/detekt/releases/download/v$DETEKT_VERSION/detekt-cli-$DETEKT_VERSION.zip"
            unzip "detekt-cli-$DETEKT_VERSION.zip"
            chmod +x "./detekt-cli-$DETEKT_VERSION/bin/detekt-cli"
            ./detekt-cli-$DETEKT_VERSION/bin/detekt-cli --report md:detekt.md
      - store_artifacts:
          path: detekt.md
          destination: detekt.md

  diktat:
    docker:
      - image: cimg/openjdk:21.0-browsers
    steps:
      - checkout
      - run:
          name: Install Diktat
          # language="shell script"
          command: |
            curl -sSLO https://github.com/saveourtool/diktat/releases/download/v2.0.0/diktat
            chmod a+x diktat
            ./diktat src/main/kotlin src/test/kotlin

  eslint:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - restore_npm_cache
      - run:
          name: Run ESLint
          command: npx eslint .

  stylelint:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - restore_npm_cache
      - run:
          name: Run Stylelint
          command: npx stylelint src/main/**/*.scss

  esbuild-check:
    docker:
      - image: cimg/base:stable
    parameters:
      node-version:
        type: string
    steps:
      - checkout
      - restore_npm_cache
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Check if esbuild is installed
          # language="shell script"
          command: |
            rm -rf ./build
            node assets-pipeline.mjs
            ls -l -R ./build

  compile:
    executor: gradle-executor
    steps:
      - checkout
      - restore_npm_cache
      - restore_gradle_cache
      - run:
          name: Compile App & Tests
          command: ./gradlew testClasses --build-cache
      - save_gradle_cache
      - save_npm_cache
      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    parallelism: 2
    executor: gradle-executor
    steps:
      - checkout
      - restore_npm_cache
      - restore_gradle_cache
      - attach_workspace:
          at: .
      - run:
          name: Run tests in parallel
          # language="shell script"
          command: |
            pushd src/test/kotlin
              # Get list of classnames of tests that should run on this node
              CLASSNAMES=$(circleci tests glob "**/**Test.kt" \
                | cut -c 1- | sed 's@/@.@g' \
                | sed 's/.\{3\}$//' \
                | circleci tests split --split-by=timings --timings-type=classname)
            popd
            # Format the arguments to "./gradlew test"
            GRADLE_ARGS=$(echo $CLASSNAMES | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
            echo "Prepared arguments for Gradle: $GRADLE_ARGS"
            ./gradlew test --build-cache $GRADLE_ARGS
      - store_test_results_artifacts

  accessibility-test:
    executor: gradle-executor
    steps:
      - checkout
      - restore_npm_cache
      - restore_gradle_cache
      - attach_workspace:
          at: .
      - run:
          name: Run Tests & Checks
          command: ./gradlew accessibilityTest --build-cache
      - store_test_results_artifacts

  docker-build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker pull build image
          # language="shell script"
          command: |
            image=$(cat Dockerfile | grep "AS build" | awk -F" " '{ print $2 }' | xargs)
            docker pull "$image"
      - run:
          name: Build Docker image
          # language="shell script"
          command: |
            docker build --progress plain -t "hyginia:latest" .
      - run:
          name: Test Docker image
          # language="shell script"
          command : |
            containerId=$(docker run -d --rm --publish 8080:8080 --name citest "hyginia:latest")
            curl -I http://citest:8080/ || echo "Ooops, curl failed"
            docker container logs "$containerId"
            sleep 10
            docker container logs "$containerId"
            docker container logs "$containerId" | grep "Server Running" || (echo "Server is NOT running after 10 secs" && exit 1)
            
            

  lighthouse:
    executor: gradle-executor
    steps:
      - checkout
      - restore_npm_cache
      - restore_gradle_cache
      - run:
          name: Install Lighthouse CI
          command: npm install
      - run:
          name: Build application
          command: ./gradlew classes
      - run:
          name: Lighthouse CI
          command: npx lhci collect && npx lhci assert

workflows:
  lighthouse:
    description: "Collect and assert Lighthouse CI analysis"
    jobs:
      - lighthouse

  build_and_test:
    description: "Build & Test"
    jobs:
      - ktlint
      - detekt
      - diktat
      - eslint
      - stylelint
      - esbuild-check:
          matrix:
            parameters:
              node-version: ["18.19.0", "20.11.0"]
      - compile:
          requires:
            - ktlint
            - detekt
            - diktat
            - eslint
            - stylelint
            - esbuild-check
      - test:
          requires:
            - compile
      - accessibility-test:
          requires:
            - compile
      - docker-build:
          requires:
            - test
            - accessibility-test