version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/idanelh/ktlint
  ktlint: idanelh/ktlint@1.0.1

executors:
  gradle-executor:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:21.0.2-browsers

commands:
  # https://circleci.com/docs/reusing-config/#authoring-reusable-commands
  restore_all_caches:
    description: "Restore Gradle wrapper, Gradle dependencies, and npm dependencies caches"
    steps:
      - restore_cache:
          name: Restore gradle-wrapper cache
          keys:
            - v3-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v3-gradle-wrapper-
      - run:
          name: Generate gradle cache key
          command: md5sum **/*.kts gradle.properties > /tmp/deps-gradle-cache-key
      - restore_cache:
          name: Restore Gradle cache
          keys:
            - v3-gradle-deps-{{ checksum "/tmp/deps-gradle-cache-key" }}
            - v3-gradle-deps-
      - restore_cache:
          name: Restore npm cache
          keys:
            - v3-npm-deps-{{ checksum "package-lock.json" }}
            - v3-npm-deps-

  save_all_caches:
    description: "Save Gradle wrapper, Gradle dependencies, and npm dependencies caches"
    steps:
      - save_cache:
          name: Save Gradle wrapper cache
          paths:
            - ~/.gradle/wrapper
          key: v3-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Generate gradle cache key
          command: md5sum **/*.kts gradle.properties > /tmp/deps-gradle-cache-key
      - save_cache:
          name: Save Gradle cache
          key: v3-gradle-deps-{{ checksum "/tmp/deps-gradle-cache-key" }}
          paths:
            - ~/.gradle/caches
      - save_cache:
          name: Save npm cache
          key: v3-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  store_test_results_artifacts:
    description: "Store test results"
    steps:
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always

jobs:
  ktlint:
    docker:
      - image: cimg/openjdk:21.0.2-browsers
    steps:
      - checkout
      - ktlint/install:
          version: 1.1.1
      - ktlint/lint:
          working-directory: ~/project

  detekt:
    docker:
      - image: cimg/openjdk:21.0-browsers
    environment:
      DETEKT_VERSION: "1.23.3"
    steps:
      - checkout
      - run:
          name: Install Detekt
          # language="shell script"
          command: |
            curl -sSLO "https://github.com/detekt/detekt/releases/download/v$DETEKT_VERSION/detekt-cli-$DETEKT_VERSION.zip"
            unzip "detekt-cli-$DETEKT_VERSION.zip"
            chmod +x "./detekt-cli-$DETEKT_VERSION/bin/detekt-cli"
            ./detekt-cli-$DETEKT_VERSION/bin/detekt-cli --report md:detekt.md
      - store_artifacts:
          path: detekt.md
          destination: detekt.md

  compile:
    executor: gradle-executor
    steps:
      - checkout
      - restore_all_caches
      - run:
          name: Compile App & Tests
          command: ./gradlew testClasses --build-cache
      - save_all_caches
      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    executor: gradle-executor
    steps:
      - checkout
      - restore_all_caches
      - attach_workspace:
          at: .
      - run:
          name: Run Tests & Checks
          command: ./gradlew check --build-cache -x accessibilityTest
      - store_test_results_artifacts

  accessibility-test:
    executor: gradle-executor
    steps:
      - checkout
      - restore_all_caches
      - attach_workspace:
          at: .
      - run:
          name: Run Tests & Checks
          command: ./gradlew accessibilityTest --build-cache
      - store_test_results_artifacts

  parallel-test:
    parallelism: 2
    executor: gradle-executor
    steps:
      - checkout
      - restore_all_caches
      - attach_workspace:
          at: .
      - run:
          name: Run tests in parallel
          # language="shell script"
          command: |
            pushd src/test/kotlin
              # Get list of classnames of tests that should run on this node
              CLASSNAMES=$(circleci tests glob "**/**Test.kt" \
                | cut -c 1- | sed 's@/@.@g' \
                | sed 's/.\{3\}$//' \
                | circleci tests split --split-by=timings --timings-type=classname)
            popd
            # Format the arguments to "./gradlew test"
            GRADLE_ARGS=$(echo $CLASSNAMES | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
            echo "Prepared arguments for Gradle: $GRADLE_ARGS"
            ./gradlew test --build-cache $GRADLE_ARGS
      - store_test_results_artifacts

workflows:
  build_and_test:
    jobs:
      - ktlint
      - detekt
      - compile:
          requires:
            - ktlint
            - detekt
      - test:
          requires:
            - compile
      - parallel-test:
          requires:
            - compile
      - accessibility-test:
          requires:
            - compile