version: 2.1

orbs:
  ktlint: idanelh/ktlint@1.0.1

jobs:
  ktlint:
    docker:
      - image: cimg/openjdk:21.0.2-browsers
    steps:
      - checkout
      - ktlint/install:
          version: 1.1.1
      - ktlint/lint:
          working-directory: ~/project

  compile:
    docker:
      - image: cimg/openjdk:21.0.2-browsers
    steps:
      - checkout
      - run: ./gradlew testClasses

  test:
    docker:
      - image: cimg/openjdk:21.0.2-browsers
    steps:
      - checkout
      - run: ./gradlew check

workflows:
  build_and_test:
    jobs:
      - ktlint
      - build:
          requires:
            - ktlint
      - test:
          requires:
            - build